#on:
#  push:
#    tags:
#      - '*.*.*'

name: Release

jobs:
  release:
    name: Release Packaging
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:  [x86_64-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run:
          sudo apt-get install --yes libwayland-dev libegl1-mesa-dev
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}
      - name: Release Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Generate man pages
        run: |
            sudo apt-get install --yes scdoc
            scdoc < man/wpaperd-output.5.scd > man/wpaperd-output.5
      - name: Strip binary
        run: |
            strip target/${{ matrix.target }}/release/wpaperd
            strip target/${{ matrix.target }}/release/wpaperctl
      - name: Create tarball
        run: |
            cp target/${{ matrix.target }}/release/wpaperd wpaperd
            cp target/${{ matrix.target }}/release/wpaperctl wpaperctl
            tar -cvf wpaperd-${{ matrix.target }}.tar.zst \
                wpaperd \
                wpaperctl \
                man/wpaperd-output.5 \
                README.md \
                LICENSE.md \
                install.yml
      - name: Upload release tarball
        uses: softprops/action-gh-release@v1
        with:
          files: wpaperd-${{ matrix.target }}.tar.zst
